### ISSUE TITLE
Manage Media not available

### ISSUE THREAD

**Issue by shishilpatel** [netflie/whatsapp-cloud-api#104]
Hello Dear Friends,

As I am testing this code from last 10 to 15 days, but I didnt found the way to download media or Get Media Id from API.

That would be great if you this as a part of this plugin.

I have created the code to pull media which is sent by users to us + I have downloaded that media to local system.

I want that someone add these code in this repository

**Comment by aalbarca** [comment]
Hi,

Please, check the README or see https://github.com/netflie/whatsapp-cloud-api/discussions/103

Best regards,
Alex.
