### ISSUE TITLE
missing message type request_welcome in webhook

### ISSUE THREAD

**Issue by medalist1981** [netflie/whatsapp-cloud-api#171]
If the user is starting a new chat instance in whatsapp, there is a webhook notification with type request_welcome.
This type is not handled in the MessageNotificationFactory::buildMessageNotification

**Comment by aalbarca** [comment]
Hi @medalist1981 

Can you please open a PR with the fix? Its very easy. You have a payload example here: https://developers.facebook.com/docs/whatsapp/cloud-api/phone-numbers/conversational-components#webhook-payload

Thanks.

**Comment by aalbarca** [comment]
Closed by inactivity
