### ISSUE TITLE
Param text cannot have new-line/tab characters or more than 4 consecutive spaces

### ISSUE THREAD

**Issue by shoyshai** [netflie/whatsapp-cloud-api#201]
Hello,
I am trying to send an image template, with caption in its body but getting the error as "Param text cannot have new-line/tab characters or more than 4 consecutive spaces" the image caption contains spaces at new paragraphs, but the same template is being sent from other provides..

**Comment by aalbarca** [comment]
The error is thrown by Whatsapp API not from this package.

Try to find the solution on StackOverflow: https://stackoverflow.com/questions/75117117/whatsapp-cloud-template-not-allowing-line-break-in-variable-text
