### ISSUE TITLE

   from twilio.rest import Client
   from flask import Flask, request, redirect
   from twilio.twiml.messaging_response import MessagingResponse

   app = Flask(__name__)

   @app.route("/webhook", methods=['POST'])
   def webhook():
       body = request.values.get('Body', None)

       resp = MessagingResponse()
       resp.message("You said: {}".format(body))

       return str(resp)

   if __name__ == "__main__":
       app.run(debug=True)
   

### ISSUE THREAD

**Issue by JezebellaJess** [netflie/whatsapp-cloud-api#204]

**Comment by Alunicstar** [comment]
from twilio.rest import Client
   from flask import Flask, request, redirect
   from twilio.twiml.messaging_response import MessagingResponse

   app = Flask(__name__)

   @app.route("/webhook", methods=['POST'])
   def webhook():
       body = request.values.get('Body', None)

       resp = MessagingResponse()
       resp.message("You said: {}".format(body))

       return str(resp)

   if __name__ == "__main__":
       app.run(debug=True)

**Comment by Alunicstar** [comment]
> 
   from twilio.rest import Client
   from flask import Flask, request, redirect
   from twilio.twiml.messaging_response import MessagingResponse

   app = Flask(__name__)

   @app.route("/webhook", methods=['POST'])
   def webhook():
       body = request.values.get('Body', None)

       resp = MessagingResponse()
       resp.message("You said: {}".format(body))

       return str(resp)

   if __name__ == "__main__":
       app.run(debug=True)

**Comment by aalbarca** [comment]
Sorry @JezebellaJess but that error is not from this package. This is a PHP package not a python.
