### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by pravnyadv** [netflie/whatsapp-cloud-api#206]
@aalbarca can you please draft a new release so i can pull updated code from composer?

**Comment by aindot** [comment]
Hello, 
I'm wondering, would changing the release to 'dev-main' be sufficient ?
```json
"require": {
        "php": "^8.2",
        "guzzlehttp/guzzle": "^7.8",
        "laravel/framework": "^11.9",
        "laravel/sanctum": "^4.0",
        "laravel/tinker": "^2.9",
        "league/flysystem-aws-s3-v3": "^3.0",
        "netflie/whatsapp-cloud-api": "dev-main"
    },
```

**Comment by pravnyadv** [comment]
Yes, It will be sufficient

Thanks

**Comment by aalbarca** [comment]
Hi  @pravnyadv 

A new release is pending of the following PR: 
https://github.com/netflie/whatsapp-cloud-api/pull/194
https://github.com/netflie/whatsapp-cloud-api/pull/193

But the author (@derrickobedgiu1) closed, sadly, the PR :S

**Comment by aalbarca** [comment]
@pravnyadv done https://github.com/netflie/whatsapp-cloud-api/releases/tag/2.2.1
