### ISSUE TITLE
Support php version 7.0?

### ISSUE THREAD

**Issue by umagenta683** [netflie/whatsapp-cloud-api#28]
Any possibility to make a release that can run on php version 7.0? Our system runs on this version..

Great work!

**Comment by netflie** [comment]
We can support obsolete and insecure php versions. Please upgrade your system to 7.4 or higher.

Thanks.

**Comment by umagenta683** [comment]
Thanks for your reply. Because of my e-com environment we can't upgrade to a higher php version because it would break some extensions. Is it really not possible to make a 7.0 version? Would help me a lot.

Thanks!

**Comment by netflie** [comment]
Sorry, we can support obsolete php versions. Please, if  you need some custom development you can hire our services at hola@netflie.es

Best regards.
