### ISSUE TITLE
How to change graph API version from 13.0 to 14.0

### ISSUE THREAD

**Issue by Dasinfomedia2** [netflie/whatsapp-cloud-api#36]
I need to change the version. how can I do it?

**Comment by netflie** [comment]
Hello,

Please, check the constructor of the super class https://github.com/netflie/whatsapp-cloud-api/blob/main/src/WhatsAppCloudApi.php.

You can change the Api version setting the "graph_version" config key.

**Comment by Dasinfomedia2** [comment]
Yes, found that.
Thanks for your reply.

**Comment by boynet** [comment]
I wonder is it compatible with 13v for whatsapp cloud?
