### ISSUE TITLE
How to show the return of the request?

### ISSUE THREAD

**Issue by jord3v** [netflie/whatsapp-cloud-api#37]
How to show the return of the request?

The package is working perfectly, but in the documentation I could not bring the result of the request.

**Comment by netflie** [comment]
Hi,

All public class from the superclass [WhatsAppCloudApi](https://github.com/netflie/whatsapp-cloud-api/blob/main/src/WhatsAppCloudApi.php) return a [Response](https://github.com/netflie/whatsapp-cloud-api/blob/main/src/Response.php) object. Please, check the public methods of Response class.

By the way you can send your questions in the future in the [Discussion](https://github.com/netflie/whatsapp-cloud-api/discussions) forum.

Thanks,
Álex.
