### ISSUE TITLE
error showing

### ISSUE THREAD

**Issue by lyarinet** [netflie/whatsapp-cloud-api#38]
Message: syntax error, unexpected 'WhatsAppCloudApiApp' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

Filename: /var/www/html/application/third_party/whatsapp/vendor/netflie/whatsapp-cloud-api/src/WhatsAppCloudApi.php

Line Number: 39

**Comment by netflie** [comment]
Hi @lyarinet can you report more info about the error? Which PHP version are you using? Thanks.
