### ISSUE TITLE
No se mandan mensajes individuales sin plantilla

### ISSUE THREAD

**Issue by daniel89fg** [netflie/whatsapp-cloud-api#52]
Hola.

Estoy probando la librería pero me es imposible enviar un mensaje individual, solo me funciona si uso una plantilla. Adjunto debajo mensaje de respuesta al enviar un mensaje individual usando sendTextMessage(), el mensaje nunca llega. ¿alguna idea?. Gracias.

**Comment by netflie** [comment]
Hola @daniel89fg

Para usar esta librería es importante conocer primero los flujos de trabajos de WhatsApp que encuentras en la documentación oficial.

Meta únicamente permite iniciar conversaciones enviando mensajes de tipo template. Una vez el usuario contesta entonces se abre una ventana de tiempo de 24 horas donde puedes interactuar con él a través del resto de tipo de mensajes.

Pasadas las 24 horas deberás iniciar una nueva sesión enviando otra vez un template con respuesta, o bien porque el usuario inicia él una nueva conversación.

Saludos.
