### ISSUE TITLE
Can I make other users participate in the conversation? 

### ISSUE THREAD

**Issue by tmcdiscord** [netflie/whatsapp-cloud-api#53]
I'm a backend devleoper, and after I have used my phone number as a Whatsapp Cloud API, I cannot seem to access it through my phone whatsapp application. 

So I was wondering if I can use this PHP API to grant access to my client to see his customers interactions with the conversation? And also reply to them?

Thanks

**Comment by netflie** [comment]
That's not supported by WhatsApp Cloud Api.
