### ISSUE TITLE
Subir archivos a Whatsapp Cloud

### ISSUE THREAD

**Issue by daniel89fg** [netflie/whatsapp-cloud-api#54]
Hola.

La librería es capaz de enviar archivos median link o mediante el id que proporciona whatsapp cloud, pero... ¿tenéis algun ejemplo de como enviar el archivo para alojarlo en whatsapp cloud y recibir el id?.

Gracias.

**Comment by netflie** [comment]
Hola,

La versión de esta librería en PHP todavía no ofrece soporte para la subida de archivos a la nube de Whatsapp, lo siento.

Un saludo.
