### ISSUE TITLE
Como validar conexión

### ISSUE THREAD

**Issue by daniel89fg** [netflie/whatsapp-cloud-api#59]
Hola.

Cuando realizamos la conexión con:
`$whatsapp_cloud_api = new WhatsAppCloudApi([
    'from_phone_number_id' => 'your-configured-from-phone-number-id',
    'access_token' => 'your-facebook-whatsapp-application-token',
]);`

¿Como podemos verificar que la conexión fue exitosa?

**Comment by netflie** [comment]
Hola,

Ahí no estás realizando ninguna conexión a ningún nado únicamente inicializando la superclase que interactuara con la API.

Deberás hacer una llamada que interaccione con la api, por ejemplo, sendTemplate.

Recuerda que estás utilizando el apartado de Issues para realizar preguntas y esto no es correcto. Debes utilizar la sección Discussions. 

Saludos.
