### ISSUE TITLE
Fatal error: Uncaught Error: Class "Component"

### ISSUE THREAD

**Issue by bihariraj** [netflie/whatsapp-cloud-api#6]
Fatal error: Uncaught Error: Class "Component" not found in C:\xampp\htdocs\wpnew\b\whatsapp-cloud-api\test.php:49 Stack trace: #0 {main} thrown in C:\xampp\htdocs\wpnew\b\whatsapp-cloud-api\test.php on line 49

**Comment by netflie** [comment]
Hi,

Please can you show the code of your test.php file? Thanks.

**Comment by bihariraj** [comment]
I have fixed this issue, thankyou

**Comment by Cesar-jpg** [comment]
How you fixed? I have a similar error
