### ISSUE TITLE
No puedo enviar mensaje 

### ISSUE THREAD

**Issue by Cesar-jpg** [netflie/whatsapp-cloud-api#66]
Estoy intentando usar el SDK, ya confirmé y si se envían los mensajes por la consola de Facebook, pero por mi web me aparecen distintos errores

Este es el código incrustado como está en la documentación 
![image](https://user-images.githubusercontent.com/70874164/209196060-f4551a49-2af8-44a5-b838-33b933e58e5d.png)

y este es el error 
![image](https://user-images.githubusercontent.com/70874164/209196178-f6730453-deeb-4ced-b846-0dc8501a5ab1.png)

Si modifico para que encuentre el archivo:
![image](https://user-images.githubusercontent.com/70874164/209196369-ca911c75-b6e0-4843-bc10-60d08e7721bd.png)

Entonces me aparece lo siguiente:
![image](https://user-images.githubusercontent.com/70874164/209196420-9be35cb0-9546-4145-98ae-d7997b174729.png)

Ya intente varias cosas, ya instale todo por composer y aun así no lo encuentra, descargue los archivos y los ingresé a la carpeta de mi proyecto y noté que no está la carpeta "vendor" y "autoload.php"

Cambie el nombre de la carpeta que decia whatsapp-app-cloud-api-main a WhatsAppCloudApi y me dice que no encuentra la clase 
![image](https://user-images.githubusercontent.com/70874164/209197661-475676fb-e788-463e-8605-45264bacf3c8.png)

**Comment by netflie** [comment]
Hola.

Veo que te has bajado el repositorio en vez de haberlo instalado con composer. Si no utilizas un autoloader entonces tu código no va a saber descubrir las clases del paquete.

Tienes que hacer hacer `composer install`, luego `composer require netflie/whatsapp-cloud-api` y finalmente `composer dump-autoload`. Ahora ya tendrás el archivo que de autoload en la carpeta vendor que se habrá generado.

Saludos.

**Comment by Cesar-jpg** [comment]
Listo, ya tenía instalado bajado el repositorio, pero no sabía que él, autoload lo teníamos que crear (primera vez que uso composer). Después de instalarlo tuve que buscar la carpeta de vendor para integrarla a la carpeta de mi proyecto, no sé si sea eso correcto, pero me pareció lo más lógico, muchas gracias.
