### ISSUE TITLE
Webhook notifications 2.0 updated new version.

### ISSUE THREAD

**Issue by murugapandiyan** [netflie/whatsapp-cloud-api#81]
after your upgrading netflie, try to get notification ,

the Webhook verification is working good. 

Webhook notifications not working. 

kindly to the needful to solve this issue to guide ...thanks 
below code : 

require '../vendor/autoload.php';

define('STDOUT', fopen('php://stdout', 'w'));

use Netflie\WhatsAppCloudApi\WebHook;

$payload = file_get_contents('php://input');
fwrite(STDOUT, print_r($payload, true) . "\n");

// Instantiate the Webhook super class.
$webhook = new WebHook();

fwrite(STDOUT, print_r($webhook->read(json_decode($payload, true)), true) . "\n");

**Comment by aalbarca** [comment]
Hi @murugapandiyan 

It's just a sample. You have to adapt the code to the characteristics of your project.

BTW, when you open a issue please provide some screenshots or code about why the code is not working. Just say "the code doens't work" is not helpful.

Thanks.
