### ISSUE TITLE
Curl error

### ISSUE THREAD

**Issue by heromiyo** [netflie/whatsapp-cloud-api#85]
local.ERROR: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://graph.facebook.com/v15.0/108949415252785/messages {"exception":"[object] (GuzzleHttp\\Exception\\RequestException(code: 0): cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://graph.facebook.com/v15.0/108949415252785/messages at D:\\CODE\\bumi_staging\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlFactory.php:211)
[stacktrace]

Am getting this error when receiving webhook message from whatsapp

**Comment by aalbarca** [comment]
Sorry but this is not a problem with this library. It seems a problem with your server configuration.
