### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by heromiyo** [netflie/whatsapp-cloud-api#86]
Hi am using the basic example for sendMessage but am getting this error which am not sure what is wrong 

[2023-02-02 12:46:32] production.ERROR:  {"exception":"[object] (Netflie\\WhatsAppCloudApi\\Response\\ResponseException(code: 0):  at /var/www/staging.loans/vendor/netflie/whatsapp-cloud-api/src/Response.php:150)
[stacktrace]
#0 /var/www/staging.loans/vendor/netflie/whatsapp-cloud-api/src/Client.php(62): Netflie\\WhatsAppCloudApi\\Response->throwException()
#1 /var/www/staging.loans/vendor/netflie/whatsapp-cloud-api/src/WhatsAppCloudApi.php(73): Netflie\\WhatsAppCloudApi\\Client->sendMessage()
#2 /var/www/staging.loans/app/Http/Controllers/WhatsappController.php(34): Netflie\\WhatsAppCloudApi\\WhatsAppCloudApi->sendTextMessage()
#3 /var/www/staging.loans/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\WhatsappController->index()
#4 /var/www/staging.loans/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#5 /var/www/staging.loans/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#6 /var/www/staging.loans/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#7 /var/www/staging.loans/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#8 /var/www/staging.loans/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()

**Comment by aalbarca** [comment]
Please @heromiyo use the Issues sections just to report issues with the code. 

Please, you have to catch the error: https://github.com/netflie/whatsapp-cloud-api#message-response
