### ISSUE TITLE
The type of message is not explicit

### ISSUE THREAD

**Issue by usyeimar** [netflie/whatsapp-cloud-api#93]
![image](https://user-images.githubusercontent.com/71295346/221332450-db2439c1-15b8-481a-9a41-be7c92618c55.png)
# Hello
**I was looking in the doc if there was any method that would allow to explicitly extract the type of message.**

I get very confused when capturing a Media type message, since a Media type message can be an Image, a video, an audio, etc.

When processing these types I can't capture the specific type of message

I would really appreciate your help with this issue Alex Albarca @aalbarca

**Comment by aalbarca** [comment]
Hi!

This is not a issue. Please request a feature on Discussions forum.

Duplicated https://github.com/netflie/whatsapp-cloud-api/discussions/92
